Groupware.Base/Controllers/Common/LoginController.cs
using DAO;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace Groupware.Base.Controllers.common
{
    public class LoginController : Controller
    {
        //
        // GET: /Login/

        public ActionResult Index( )
        {

            return View("~/views/common/Login.cshtml");
        }

		[HttpPost]
		public JObject LoginProcess()
		{
			JObject jsonObj = new JObject();
			string strId = Request.Form["id"];

			DaoEmp daoEmp = new DaoEmp();
			
			CEmp emp = daoEmp.getEmp(Request.Form["id"], Request.Form["passwd"]);
			if (emp == null)
			{
				jsonObj.Add("RESULT", "FAIL");
				jsonObj.Add("MSG", "해당되는 사용자가 없습니다.");
			}
			else
			{
				LoginProcess(emp);
				jsonObj.Add("RESULT", "OK");
			}

			return jsonObj;
		}

		public void LoginProcess( CEmp emp )
		{
			Session["idx"] = emp.idx;
			Session["emp_no"] = emp.emp_no;
			Session["name"] = emp.name;
			Session["id"] = emp.id;
			Session["email"] = emp.email;
			Session["reg_date"] = emp.reg_date;
			Session["mod_date"] = emp.mod_date;
			Session["is_used"] = emp.is_used;
			Session["is_admin"] = emp.is_admin;
			Session.Timeout = 240;
		}

		public ActionResult Logout()
		{
			Session.Clear();
			return Index();
		}

		public ActionResult LoginCheck()
		{
			return null;
		}
    }
}

Groupware.Base/Controllers/Layout/HeaderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Groupware.Base.Controllers.Layout
{
    public class HeaderController : Controller
    {
        //
        // GET: /Header/

        public ActionResult Index()
        {
					ViewBag.HeaderTitle = "Groupware Base";

					return PartialView("~/views/layout/Header.cshtml");
        }

    }
}

Groupware.Base/Controllers/Layout/LeftController.cs
using DAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Groupware.Base.Controllers.Layout
{
    public class LeftController : Controller
    {
        //
        // GET: /Left/

        public ActionResult Index()
        {
			IList<CCode> listTree = new List<CCode>();
			try
			{
				DaoCode daoTree = new DaoCode();
				listTree = daoTree.getCodeList("leftmenu", 0, null, 2);
				ViewBag.listTree = listTree;
			}
			catch (Exception e)
			{
				throw new Exception(e.Message);
			}

			return PartialView("~/views/layout/LeftMenu.cshtml", listTree);
        }

    }
}

Groupware.Base/Views/Shared/Blank.cshtml
@{
	ViewBag.Title = "Blank";
}


<div class="row">
	<div class="col-lg-12">

		<!-- /.panel -->
		<div class="panel panel-default">
			<div class="panel-heading">
				@ViewBag.PanelTitle
			</div>
			<!-- /.panel-heading -->
			<div class="panel-body">


			</div>
			<!-- /.panel-body -->
		</div>
		<!-- /.panel -->

	</div>
	<!-- /.col-lg-12 -->
</div>
<!-- /.row -->

Groupware.Base/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
	<!--jquery-->
	@Styles.Render("~/Content/css")
	@Scripts.Render("~/bundles/modernizr")
	@Scripts.Render("~/bundles/jquery")

	<!-- Core CSS - Include with every page -->
	@Styles.Render("~/custom/bootstrap-css")
	<link href="/font-awesome/css/font-awesome.css" rel="stylesheet">

	<!-- Page-Level Plugin CSS - Blank -->

	<!-- SB Admin CSS - Include with every page -->
	<link href="/css/sb-admin.css" rel="stylesheet" />

	<!-- Groupware JS -->
	@Scripts.Render("~/custom/common-js")

</head>
<body>

	<div id="wrapper">

		@RenderBody()
	
		@RenderSection("scripts", required: false)

	</div>
	<!-- /#wrapper -->

	<!-- Core Scripts - Include with every page -->
    @Scripts.Render("~/custom/bootstrap-js")
    <script src="/js/plugins/metisMenu/jquery.metisMenu.js"></script>

    <!-- Page-Level Plugin Scripts - Blank -->

    <!-- SB Admin Scripts - Include with every page -->
    <script src="/js/sb-admin.js"></script>

    <!-- Page-Level Demo Scripts - Blank - Use for reference -->




	<!-- Modal -->
	@*<button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
        Launch Demo Modal
    </button>*@
	<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title" id="myModalLabel">Modal title</h4>
				</div>
				<div class="modal-body"  id="myModalBody">
					
				</div>
				<div class="modal-footer">
					<button type="button" id="btn-modal-close" class="btn btn-default" data-dismiss="modal">Close</button>
					<button type="button" id="btn-modal-save" class="btn btn-primary">Save changes</button>
				</div>
			</div>
			<!-- /.modal-content -->
		</div>
		<!-- /.modal-dialog -->
	</div>
	<!-- /.modal -->

</body>
</html>

Groupware.Base/Views/Shared/_MainLayout.cshtml
@{
	if ( Session["emp_no"] == null || Session["emp_no"] == "" )
	{
		Html.RenderAction("Index", "Login");
	}
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
	<!--jquery-->
	@Styles.Render("~/Content/css")
	@Scripts.Render("~/bundles/modernizr")
	@Scripts.Render("~/bundles/jquery")

	<!-- jquery library -->
	@Scripts.Render("~/jquerylib/jstree-js")
	@Styles.Render("~/jquerylib/jstree-css")

	<!-- Core CSS - Include with every page -->
	@Styles.Render("~/custom/bootstrap-css")
	<link href="/font-awesome/css/font-awesome.css" rel="stylesheet">

	<!-- Page-Level Plugin CSS - Blank -->

	<!-- SB Admin CSS - Include with every page -->
	<link href="/css/sb-admin.css" rel="stylesheet" />

	<!-- Groupware JS -->
	@Scripts.Render("~/custom/common-js")


</head>
<body>

	<div id="wrapper">

		@{
			Html.RenderAction("Index", "Header");
			Html.RenderAction("Index", "Left");
		}
		
		<div id="page-wrapper">
			<div class="row">
				<div class="col-lg-12">
					<h1 class="page-header">@ViewBag.Title</h1>
				</div>
				<!-- /.col-lg-12 -->
			</div>
			<!-- /.row -->
			@RenderBody()
		</div>
		<!-- /#page-wrapper -->

	</div>
	<!-- /#wrapper -->
	
	@RenderSection("scripts", required: false)


	<!-- Core Scripts - Include with every page -->
    @Scripts.Render("~/custom/bootstrap-js")
    <script src="/js/plugins/metisMenu/jquery.metisMenu.js"></script>

    <!-- Page-Level Plugin Scripts - Blank -->

    <!-- SB Admin Scripts - Include with every page -->
    <script src="/js/sb-admin.js"></script>

    <!-- Page-Level Demo Scripts - Blank - Use for reference -->

	

	<!-- Modal -->
	@*<button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
        Launch Demo Modal
    </button>*@
	<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title" id="myModalLabel">Modal title</h4>
				</div>
				<div class="modal-body"  id="myModalBody">
					
				</div>
				<div class="modal-footer">
					<button type="button" id="btn-modal-close" class="btn btn-default" data-dismiss="modal">Close</button>
					<button type="button" id="btn-modal-save" class="btn btn-primary">Save changes</button>
				</div>
			</div>
			<!-- /.modal-content -->
		</div>
		<!-- /.modal-dialog -->
	</div>
	<!-- /.modal -->

</body>
</html>